### ISSUE TITLE
Expired Link

### ISSUE THREAD

**Issue by Ntshangase** [mikeconley/documents#5]
There is a link that seems to not work on your website, It's on the Home page, The name of the link is "maybe get familiar with basics" , when you click on it, It takes you to an 'expired website'.

![Screenshot (64)](https://user-images.githubusercontent.com/62051440/224417476-686d4e87-74cd-4024-b271-535c6f109e47.jpg)
![Screenshot (65)](https://user-images.githubusercontent.com/62051440/224417507-78680615-36f1-4e13-858b-bee2dc42c1d1.png)

**Comment by mikeconley** [comment]
Thanks!
